services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: brillio-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - brillio-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Laravel
  app:
    image: brillioafrica/api:latest
    container_name: brillio-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./app:/var/www/html/app
      - ./routes:/var/www/html/routes
      - ./resources:/var/www/html/resources
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/default.conf:/etc/nginx/http.d/default.conf
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./config:/var/www/html/config
      - ./docker/certbot/conf:/etc/letsencrypt
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fLk", "http://localhost:8080/up"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - brillio-network

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: brillio-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --save 60 1
    volumes:
      - redis_data:/data
    networks:
      - brillio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  brillio-network:
    driver: bridge
